export const ERROR = "ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
