export const ERROR = "ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_DELETE_ITEM = "CARD_DELETE_ITEM";
