export const ERROR = "ERROR";
export const ERROR_RESET = "ERROR_RESET";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_DELETE_ITEM = "CARD_DELETE_ITEM";
export const CART_CLEAR_ITEM = "CARD_CLEAR_ITEM";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";

export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_LOGOUT_SUCCESS = "USER_DETAILS_LOGOUT_SUCCESS";

export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";

export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

export const ORDER_LIST_ADMIN_SUCCESS = "ORDER_LIST_ADMIN_SUCCESS";
export const ORDER_LIST_ADMIN_RESET = "ORDER_LIST_ADMIN_RESET";

export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";
